name: wisdom
description: A Flutter project.

publish_to: 'none'

version: 3.0.1+1

environment:
  sdk: ">=3.0.5 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  intl: ^0.18.0
  flutter_svg: ^2.0.9
  flutter_screenutil: ^5.5.4
  flutter_zoom_drawer: ^3.0.3
  mask_text_input_formatter: ^2.4.0
  pin_code_fields: ^8.0.1
  top_snackbar_flutter: ^3.0.0+1
  url_launcher: ^6.1.7
  numberpicker: ^2.1.1
  sqflite: ^2.2.2
  http: ^0.13.5
  shared_preferences: ^2.0.15
  connectivity_plus: ^5.0.2
  swipe_refresh: ^1.0.2
  flutter_widget_from_html: ^0.15.3

  # for downloading
  sn_progress_dialog: ^1.1.3

  #  google_translator: ^1.0.0
  translator: ^0.1.7

  clipboard: ^0.1.3
  speech_to_text: ^6.1.1
  lottie: ^2.2.0  # Firebase push notification
  firebase_core: ^3.7.0
  firebase_messaging: ^15.1.4

  # Localization
  easy_localization: ^3.0.2
  provider: ^6.0.5

  # Notification
  flutter_local_notifications: ^18.0.1
  awesome_notifications: ^0.9.2
  workmanager: ^0.5.1

  expandable: ^5.0.1
  flutter_tts: ^3.6.3

  flutter_timezone: ^1.0.7

  #Splash
  flutter_native_splash: any

  # google ads
  google_mobile_ads: ^5.2.0

  #app launcher
  #  external_app_launcher: ^3.1.0

  #Text selection menu
  selectable: ^0.3.3

  # Share for text, images, file
  share_plus: ^6.3.2
  cupertino_icons: ^1.0.2

  # to show tutorial for home page
  tutorial_coach_mark: ^1.2.6
  showcaseview: ^3.0.0

  flutter_keyboard_visibility: ^6.0.0

  #flipper animation
  flip_card: ^0.7.0

  #animation for save words icon
  add_to_cart_animation: ^2.0.3

  #badge
  badges: ^3.0.2

#  adapty_flutter: ^2.4.4


  # state management
  jbaza:
    git:
      url: https://github.com/Javoh29/Jbaza
  platform_device_id:
    git:
      url: https://github.com/faridfedora/platform_device_id_kotlin_updated.git
      ref: master
  path_provider: ^2.1.2
  permission_handler: ^11.0.1
  timezone: ^0.9.2
  google_sign_in: ^6.1.6
  sign_in_with_apple: ^5.0.0
  flutter_animate: ^4.5.0
  dio: ^5.4.1
  image_picker: ^1.0.7
  cached_network_image: ^3.3.1
  flutter_facebook_auth: ^6.0.4
  sqflite_common_ffi: ^2.3.3
  logger: ^2.5.0
  gap: ^3.0.1
  yandex_mobileads: ^7.7.0
#  syncfusion_flutter_sliders: ^26.1.39
  percent_indicator: ^4.2.4
  dotted_border: ^2.1.0
  shimmer: ^3.0.0


dependency_overrides:
  intl: ^0.18.1
  win32: ^5.5.8
  device_info_plus_platform_interface: ^7.0.1
  sentry_flutter: ^7.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.1.2
  json_serializable: ^6.7.1
  flutter_lints: ^3.0.1
  # icon
  flutter_launcher_icons: ^0.13.1


flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/icon.png"
  remove_alpha_ios: true
  min_sdk_android: 21 # android min sdk min:16, default 21
  windows:
    generate: true
    image_path: "assets/images/icon.png"
    icon_size: 48 # min:48, max:256, default: 48

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/lottie/
    - assets/translations/
    - fonts/
    - assets/waio_dictionary.db
    - assets/sound/slow_spring_board.mp3

  fonts:
    - family: Montserrat
      fonts:
        - asset: fonts/Montserrat-Black.ttf
          weight: 900
          style: normal
        - asset: fonts/Montserrat-ExtraBold.ttf
          weight: 800
          style: normal
        - asset: fonts/Montserrat-Bold.ttf
          weight: 700
          style: normal
        - asset: fonts/Montserrat-SemiBold.ttf
          weight: 600
          style: normal
        - asset: fonts/Montserrat-Medium.ttf
          weight: 500
          style: normal
        - asset: fonts/Montserrat-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: fonts/Montserrat-Regular.ttf
          weight: 400
          style: normal
        - asset: fonts/Montserrat-Light.ttf
          weight: 300
          style: normal
        - asset: fonts/Montserrat-ExtraLight.ttf
          weight: 200
          style: normal
        - asset: fonts/Montserrat-Thin.ttf
          weight: 100
          style: normal

  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

flutter_native_splash:

  color: "#0063A4"
  image: assets/images/logo_icon_white.png
  color_dark: "#1F1D2B"

  android_12:
    # The image parameter sets the splash screen icon image.  If this parameter is not specified,
    # the app's launcher icon will be used instead.
    # Please note that the splash screen will be clipped to a circle on the center of the screen.
    # App icon with an icon background: This should be 960×960 pixels, and fit within a circle
    # 640 pixels in diameter.
    # App icon without an icon background: This should be 1152×1152 pixels, and fit within a circle
    # 768 pixels in diameter.
    image: assets/images/logo_icon_white_12.png

    color: "#0063A4"
    color_dark: "#1F1D2B"

  android: true
  ios: true
  web: false

  color_android: "#0063A4"
  color_dark_android: "#1F1D2B"
  color_ios: "#0063A4"
  color_dark_ios: "#1F1D2B"

  fullscreen: true