List<Map<String, String>> abbreviations = [
  {'abbr': '(abbreviation) qisqartma'},
  {'adjective': 'sifat'},
  {'adverb': 'ravish'},
  {'AmE': 'Amerika ingiliz tilisi'},
  {'AW': '(Academic Word) akademik so\'z'},
  {'BrE': 'Britanya ingiliz tilisi'},
  {'C': '(Countable) sanaladigan ot'},
  {'exclamation': 'undov bildiruvchi'},
  {'formal': 'rasmiy so\'z'},
  {'IndE': '(Indian English) Hind ingiliz tilisiga ta\'luqli'},
  {'informal': 'norasmiy so\'z'},
  {'noun': 'ot'},
  {'old use': 'eskirgan so\'z, qadimda ishlatilgan so\'z'},
  {'old-fashioned': 'urfdab qolgan so\'z'},
  {'Phrases and Idioms': 'Fe\'lli birikmalar va Iboralar'},
  {'pl': '(plural) ko\'plik'},
  {'prfix': 'old qo\'shimcha'},
  {'sl': '(singular) birlik'},
  {'suffix': 'ket qo\'shimcha'},
  {'symbol': 'belgi'},
  {'technical': 'termin, atama'},
  {'U': '(uncountable) sanalmaydigan ot'},
  {'verb': 'fe\'l'},
  {'humorous': 'hazilomus tarizda ishlatiladi'},
  {'CanE': 'Kanada ingiliz tilisi'},
  {'taboo': 'haqoratomuz'},
  {
    'slang':
        'ma\'lum bir toifadagi odamlar tomonidan asosan og\'zaki nutqda ishlatiladigan norasmiy so\'z'
  },
];
